package app.morrow.assistant;
import app.morrow.checkin.CheckIn;
import app.morrow.recommendation.Recommendation;
import app.morrow.timeline.Timeline;
import org.springframework.stereotype.Component;
import java.time.format.DateTimeFormatter;
import java.util.List;
@Component
public class PromptBuilder {
 private static final String SYSTEM_PROMPT="당신은 일상 웰니스를 지원하는 AI 어시스턴트입니다.\n\n핵심 원칙:\n- 의료 진단이나 치료를 제공하지 않습니다\n- 생체 데이터만으로 질환을 확정하지 않습니다\n- 약물 변경이나 치료 중단을 지시하지 않습니다\n- 위기 상황에서는 전문 지원을 최우선으로 안내합니다\n- 사용자의 과거 기록과 검증된 개인 메모리를 참고해 개인화된 조언을 제공합니다\n- 근거가 적은 패턴은 가능성으로 표현하고 단정하지 않습니다\n- 도움이 되지 않았다고 기록된 행동을 우선 추천하지 않습니다\n- 사용자 입력과 수정이 자동 추론보다 우선합니다\n- 공감하고 지지하는 톤으로 대화합니다\n\n사용자별 메모리는 범용 모델 학습 결과가 아니라 이 사용자의 기록에서 계산된 개인화 컨텍스트입니다.";
 public String buildSystemPrompt(){return SYSTEM_PROMPT;}
 public String buildUserContextPrompt(UserContextCollector.UserContext context){var sb=new StringBuilder();sb.append("=== 사용자 컨텍스트 ===\n\n");if(!context.memories().isEmpty()){sb.append("장기 개인화 메모리 (사용자별 저장소, 신뢰도와 근거 수 포함):\n");context.memories().stream().limit(12).forEach(m->sb.append(String.format("- [%s, 신뢰도 %.0f%%, 근거 %d] %s%s\n",m.getType(),m.getConfidence()*100,m.getEvidenceCount(),m.getSummary(),m.getNegativeEvidence()>m.getPositiveEvidence()?" (우선 추천하지 않기)":"")));}if(!context.recentCheckIns().isEmpty()){sb.append("\n최근 7일 체크인 기록:\n");context.recentCheckIns().stream().limit(10).forEach(c->sb.append(String.format("- %s: %s 상태, 원인: %s%s\n",c.getRecordedAt().format(DateTimeFormatter.ofPattern("MM/dd HH:mm")),translateStatus(c.getStatus()),c.getCause()!=null?translateCause(c.getCause()):"미기록",c.getNote()!=null?" ("+c.getNote()+")":"")));}if(!context.recentTimelines().isEmpty()){sb.append("\n최근 타임라인:\n");context.recentTimelines().stream().limit(5).forEach(t->sb.append(String.format("- %s: %s - %s\n",t.getTime(),t.getTitle(),t.getDetail())));}if(!context.recentRecommendations().isEmpty()){sb.append("\n최근 추천:\n");context.recentRecommendations().stream().limit(3).forEach(r->sb.append(String.format("- %s (상태: %s)\n  근거: %s\n",r.getTitle(),r.getStatus(),r.getRationale())));}if(!context.recentMessages().isEmpty()){sb.append("\n최근 대화 (24시간):\n");context.recentMessages().stream().limit(6).forEach(m->sb.append(String.format("- %s: %s\n",m.getRole()==AssistantMessage.Role.USER?"사용자":"AI",m.getContent().length()>100?m.getContent().substring(0,100)+"...":m.getContent())));}if(context.recentCheckIns().isEmpty()&&context.recentTimelines().isEmpty()&&context.recentRecommendations().isEmpty()){sb.append("아직 기록된 데이터가 없습니다. 체크인을 시작해보세요!\n");}return sb.toString();}

 public String buildPersonalizedFallback(UserContextCollector.UserContext context,String message){var positive=context.memories().stream().filter(m->m.getType()==app.morrow.personalization.UserMemory.Type.RECOVERY_STRATEGY&&m.getPositiveEvidence()>m.getNegativeEvidence()).findFirst();if(positive.isPresent())return"지금은 생성형 AI 연결 없이 개인화 기록으로 답하고 있어요. 이전 피드백에서는 "+positive.get().getSummary()+"으로 남아 있어요. 현재 상태에 무리가 없다면 같은 방법을 짧게 시도해 볼까요?";if(message.matches(".*(잠|수면|피곤).*"))return"최근 수면 관련 피로 기록을 참고했어요. 지금은 물 한 잔을 마시고 7분만 가볍게 움직인 뒤 상태를 다시 확인해 보세요.";return"지금은 생성형 AI 연결 없이 저장된 개인 기록으로 답하고 있어요. 현재 상태를 체크인하면 반복 패턴과 도움이 된 방법을 다음 답변부터 반영할게요.";}
 private String translateStatus(CheckIn.Status status){return switch(status){case OK->"양호";case TENSE->"긴장";case TIRED->"피로";case LOW_FOCUS->"집중력 저하";case UNCOMFORTABLE->"불편";};}
 private String translateCause(CheckIn.Cause cause){return switch(cause){case SLEEP->"수면";case WORK->"업무";case STUDY->"학업";case RELATIONSHIP->"인간관계";case PHYSICAL->"신체";case UNKNOWN->"알 수 없음";};}
}
